import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Background from "@/components/background";
import LegalLinks from "@/components/LegalLinks";
import AuthButton from "@/components/authButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen bg-black text-white`}
      >
        <Background />
        <div
          className="pointer-events-none fixed inset-0
                       bg-[radial-gradient(ellipse_at_top,rgba(0,0,0,.35),transparent_60%)]
                      before:content-[''] before:absolute before:inset-0
                      before:bg-black/30"
        ></div>
        <header
          className="fixed top-0 left-0 w-full h-14 border-b border-white/10
                    bg-black/40 backdrop-blur-sm flex items-center px-5
                    justify-between z-50 text-white"
        >
          <nav className="flex gap-4 text-sm" aria-label="주요 메뉴">
            <Link
              className="text-white/90 hover:text-white [text-shadow:0_1px_1px_rgba(0,0,0,.6)]"
              href="/"
            >
              홈
            </Link>
            <Link
              className="text-white/90 hover:text-white [text-shadow:0_1px_1px_rgba(0,0,0,.6)]"
              href="/dashboard/me"
            >
              대시보드
            </Link>
            <Link
              className="text-white/90 hover:text-white [text-shadow:0_1px_1px_rgba(0,0,0,.6)]"
              href="/games"
            >
              게임
            </Link>
            <Link
              className="text-white/90 hover:text-white [text-shadow:0_1px_1px_rgba(0,0,0,.6)]"
              href="/achievements"
            >
              업적
            </Link>
            <Link
              className="text-white/90 hover:text-white [text-shadow:0_1px_1px_rgba(0,0,0,.6)]"
              href="/ranking"
            >
              랭킹
            </Link>
            <Link
              className="text-white/90 hover:text-white [text-shadow:0_1px_1px_rgba(0,0,0,.6)]"
              href="/about"
            >
              소개
            </Link>
          </nav>
          <div className="text-sm">
            <AuthButton />
          </div>
        </header>

        <main className="pt-20 p-0">{children}</main>
        <LegalLinks />
      </body>
    </html>
  );
}
